from .main import get_data_historical,get_lastday_data,get_today_price
from .errors import ServerExeption,NoSuchStock,SomethingBadHappened
from .main import  get_today_prices_several,get_historical_for_graph,get_data_for_plotting
